# Generated by Django 5.2.7 on 2025-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=99, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(default='', max_length=99, verbose_name='website url'),
        ),
    ]
