# Generated by Django 5.2.4 on 2025-07-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=99, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
