# Generated by Django 5.2.7 on 2025-10-21 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_location_alter_user_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facebook', models.URLField(blank=True, max_length=99, verbose_name='facebook url')),
                ('twitter', models.URLField(blank=True, max_length=99, verbose_name='twitter url')),
                ('instagram', models.URLField(blank=True, max_length=99, verbose_name='instagram url')),
                ('linkedin', models.URLField(blank=True, max_length=99, verbose_name='linkedin url')),
                ('github', models.URLField(blank=True, max_length=99, verbose_name='github url')),
                ('reddit', models.URLField(blank=True, max_length=99, verbose_name='reddit url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
