# Generated by Django 5.2.7 on 2025-10-21 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_sociallinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
