# Generated by Django 5.2.7 on 2025-10-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_sociallinks_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
