# Generated by Django 5.2 on 2025-08-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=999),
        ),
    ]
