# Generated by Django 5.2.7 on 2025-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0003_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tags/'),
        ),
    ]
