# Generated by Django 5.2.7 on 2025-10-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0004_tag_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.AddField(
            model_name='tag',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tags_logo/'),
        ),
    ]
