# Generated by Django 5.2.7 on 2025-10-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_app', '0005_remove_tag_image_tag_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='logo',
        ),
        migrations.AddField(
            model_name='tag',
            name='logo_url',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
