# Generated by Django 5.2.7 on 2025-10-22 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_app', '0005_rename_published_at_post_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('L', 'Like'), ('C', 'Comment'), ('R', 'Reply')], default='L', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for', to=settings.AUTH_USER_MODEL)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_by', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='post_app.post')),
            ],
        ),
    ]
