# Generated by Django 5.2.7 on 2025-10-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_notification_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='_for',
            new_name='n_for',
        ),
    ]
