# Generated by Django 5.2.7 on 2025-10-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0005_notification_is_read_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply')], default='like', max_length=7),
        ),
    ]
