# Generated by Django 5.2.7 on 2025-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
