# Generated by Django 5.2.7 on 2025-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0007_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
