# Generated by Django 5.2.7 on 2025-10-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0006_rename_updated_comment_updated_at'),
        ('notification_app', '0008_notification_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_app.comment'),
        ),
    ]
