# Generated by Django 5.2.7 on 2025-10-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0009_alter_notification_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reference',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
