# Generated by Django 5.2 on 2025-08-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_commentlike_reply_replylike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replylike',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='replylike',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment_app.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment_app.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='ReplyLike',
        ),
    ]
