# Generated by Django 5.2.4 on 2025-08-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0005_comment_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
