# Generated by Django 5.2 on 2025-08-21 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disableComment',
            new_name='disable_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='disableLike',
            new_name='disable_like',
        ),
    ]
