# Generated by Django 5.2.4 on 2025-08-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.thumbnail'),
        ),
    ]
