# Generated by Django 5.2.4 on 2025-08-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_remove_thumbnail_post_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
