# Generated by Django 5.2 on 2025-08-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_rename_disablecomment_post_disable_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='published',
        ),
    ]
