# Generated by Django 5.2.7 on 2025-10-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
